scale: 1.0
preload: true
font-family: liberation

menu:
  audio: menu-item
  volume: 0.1

main-menu:
  audio: menu-item
  volume: 0.1

dialog-box:
  #delay: 60
  #alpha: 0.3
  #endPoint: true
  font-size: 20px
  line-height: 24px
  font-family: liberation
  mode-classic: dialog-box
  mode-fullscreen: dialog-box-full

player:
  name: player
  uuid: 00000000-0000-0000-0000-000000000000

publish:
  isbn: 000-0-00000-000-0
  name: mcap-vnjson-1.12.2 Руководство пользователя
  host: http://vn.mcvn.ru/
  token: 00000000-0000-0000-0000-000000000000

ri-api: http://vn.mcvn.ru/reindexer/api/v1/db/vnjson

discord:
  webhook: https://discord.com/api/webhooks/1212765937749729360/fNhkpzGom-N1j4nSq7FQLJCsTkznE6FMDtOI3Xpx_fodmVJOoXhAz-2TD-HtjKMcuMku